name: CI CD Docker Build and Push

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE_NAME: mid-program-project-demo

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Commit hash
        id: vars
        run: echo "GIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build Docker Image with commit hash
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.GIT_SHA }} \
                       -t ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest .

      - name: Push Docker Image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.GIT_SHA }}
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Clone the Hugging Face Space
            git clone https://oauth2:${HF_TOKEN}@huggingface.co/spaces/nachikethmurthy666/mid-project-project hf-app

            # Create a safe temp directory outside the repo path
            TEMP_DIR=$(mktemp -d)

            # Copy everything from the current repo into the temp folder
            rsync -av --delete --exclude=".git" ./ $TEMP_DIR/

            # Sync from temp folder to the cloned hf-app
            rsync -av --delete $TEMP_DIR/ hf-app/

            # Commit and push
            cd hf-app
            git config user.email "actions@github.com"
            git config user.name "GitHub Actions"
            git add .
            git commit -m "Deploy to Hugging Face = ${{ env.GIT_SHA }}" || echo "No changes"
            git push https://oauth2:${HF_TOKEN}@huggingface.co/spaces/nachikethmurthy666/mid-project-project

